### ISSUE TITLE
Can't open Ipython note book ends in Time out

### ISSUE THREAD

**Issue by Rahulvks** [mGalarnyk/Installations_Mac_Ubuntu_Windows#3]
After installed anaconda. 

Checked in nohup kernel is active 
Jupyter$ cat nohup.out 
 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
 NotebookApp] 0 active kernels 
 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8888/

When i copied Notebook https with my public ip with port it end up in time out. 

Kindly help

**Comment by mGalarnyk** [comment]
Sorry this might be just for your system. I need a reproducible error or a least your system information.
