### ISSUE TITLE
AWS blogpost question

### ISSUE THREAD

**Issue by sagar-m** [mGalarnyk/Installations_Mac_Ubuntu_Windows#5]
Hi Michael, I had a question related to AWS related [blogpost](https://www.datacamp.com/community/tutorials/aws-ec2-beginner-tutorial) you had written. I am stuck on point 15. Any help, would be highly appreciated! Thank you very much.

> 15.Open your rdp file. Click on continue. If your local computer is a Mac, you will need to download "Microsoft Remote Desktop" from the App Store to be able to open your rdp file.

I tried using both "microsoft remote desktop" and "microsoft remote desktop beta" for mac.

**_This was the instruction I followed from AWS:_**

[Mac OS X] For the Microsoft Remote Desktop app, choose New and do the following:

For PC Name, enter the IPv6 address of your Windows instance; for example,2001:db8:1234:1a00:9691:9503:25ad:1761.

For User name, enter Administrator.

Close the dialog box. Under My Desktops, select the connection and choose Start.

-----

And these are my AWS details:
Public DNS | ec2-18-218-163-206.us-east-2.compute.amazonaws.com
User name| Administrator

------
However, I get an error, which is:
We couldn't connect to the remote PC. Make sure the PC is turned on and connected to the network, and that remote access is enabled.
Error code: 0x204

**Comment by mGalarnyk** [comment]
1. Are you sure the instance is running? 

2. What security settings did you put on the instance? 

It usually it as easy as right clicking and opening the file if security isn't an issue.

**Comment by sagar-m** [comment]
Yes, the instance is running. Everything until #15 in your blog is working.

I think I am not adding the details correctly in microsoft remote desktop. Attaching few snapshots of its settings and the error message.

![aws 1](https://user-images.githubusercontent.com/27808289/35625961-2fdfdf3e-06ba-11e8-81fa-1b7262f35d5c.png)
![micro_dt_error](https://user-images.githubusercontent.com/27808289/35625979-3b10f8b6-06ba-11e8-8baa-5f7d178ad096.png)
![aws setting1](https://user-images.githubusercontent.com/27808289/35625984-3f53ca2a-06ba-11e8-80e4-a7c393e61e06.png)
![micro_dt_setting2](https://user-images.githubusercontent.com/27808289/35625989-4360195c-06ba-11e8-9348-6028bbad1b63.png)
![aws setting1](https://user-images.githubusercontent.com/27808289/35625993-46f43a62-06ba-11e8-9643-5faf3b22d7ee.png)

**Comment by sagar-m** [comment]
Yes, the instance is running. Everything until #15 in your blog is working.

I think I am not adding the details correctly in microsoft remote desktop. Attaching few snapshots of its settings and the error message. I am confused what should be the server name in the settings? The Public DNS name or IPv4 public IP? Thank you.

![aws 1](https://user-images.githubusercontent.com/27808289/35625961-2fdfdf3e-06ba-11e8-81fa-1b7262f35d5c.png)
![micro_dt_error](https://user-images.githubusercontent.com/27808289/35625979-3b10f8b6-06ba-11e8-8baa-5f7d178ad096.png)
![aws setting1](https://user-images.githubusercontent.com/27808289/35625984-3f53ca2a-06ba-11e8-80e4-a7c393e61e06.png)
![micro_dt_setting2](https://user-images.githubusercontent.com/27808289/35625989-4360195c-06ba-11e8-9348-6028bbad1b63.png)
![aws setting1](https://user-images.githubusercontent.com/27808289/35625993-46f43a62-06ba-11e8-9643-5faf3b22d7ee.png)

**Comment by mGalarnyk** [comment]
I will make a youtube video this weekend on this to make it easier for you :)

 It usually is right click and open with Microsoft Remote Desktop to get to the desktop.

**Comment by sagar-m** [comment]
Thanks! Anything to make [AWS](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/connecting_to_windows_instance.html) work would be appreciated :) 

By the way, if I just open the .rdp file as per #15 in your blog, this is what happens. (please see attached image). First, I tried putting "administrator" in the computer tab, and Second, I tried putting the public DNS.

Error: "Unable to connect to remote PC. Please verify Remote Desktop is enabled, the remote PC is turned on and available on the network, and then try again."

![opening rdp file1](https://user-images.githubusercontent.com/27808289/35662277-467712d4-073d-11e8-9e16-5a90d511b98e.png)
![rdp error2](https://user-images.githubusercontent.com/27808289/35662280-4a81deea-073d-11e8-8d77-4594d943ddc1.png)
![rdc preferences](https://user-images.githubusercontent.com/27808289/35668575-f99291da-0757-11e8-8d39-1f3823ed4831.png)

**Comment by sagar-m** [comment]
Thank you so much. And apologies for the delay in reply, I was traveling for the last eight days.

I tried again today, and followed the steps you have written. This time, 

## I downloaded an upgrade version 10.0 of "microsoft remote desktop" from mac app store.

## Created a new instance in AWS

## Just right clicked the .rdp file to open with "microsoft remote desktop".

However, I am still getting an error. The image of the error has been attached. This is getting very frustrating. I went through some solutions on AWS support [link](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/connecting_to_windows_instance.html#connect-rdp), and did not find an answer to my issue.

![feb 16 error](https://user-images.githubusercontent.com/27808289/36298469-4c9825e4-131e-11e8-8dfc-62282d3fb093.png)

**Comment by mGalarnyk** [comment]
I made a video hopefully solving this issue. I know it is probably too late, but who knows.
https://www.youtube.com/watch?v=mf5u2chPBjY

**Comment by mGalarnyk** [comment]
also I used Microsoft Remote Desktop 8 instead of 10. I find 10 to be very difficult to work with currently.

**Comment by sagar-m** [comment]
Hello. Great. Thanks. Yes, I was waiting for your video!

**Comment by mGalarnyk** [comment]
No problem :)
